# Generated by Django 5.1.4 on 2024-12-30 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='First Name')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last Active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=10, verbose_name='User Status')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('pages_count', models.IntegerField(default=0, max_length=10, verbose_name='Number of pages read')),
                ('read_books_name_count', models.IntegerField(verbose_name='Number of books read')),
                ('books_want_read_count', models.IntegerField(verbose_name='The number of books you want to read')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='BooksRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=256, verbose_name='Book Title')),
                ('date_read', models.DateField(verbose_name='Date Read')),
                ('pages_read', models.IntegerField(default=0, verbose_name='Pages Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.telegramuser', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PagesRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('pages_read', models.IntegerField(default=0, verbose_name='Pages Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_pages', to='TelegramBot.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily Pages Read',
                'verbose_name_plural': 'Daily Pages Read',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
